services:
  # Base de datos MySQL
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: planetario_db
      MYSQL_ROOT_HOST: '%'          
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  # Backend (Node + Express)
  backend:

    # **Desarrollo** descomentar esta linea y comenta la seccion de 'image: …'
    build: ./backend

    # **En el equipo destino**, despues de hacer `docker load -i planetario-backend-image.tar`,
    # image: planetario-backend:latest

    command: sh -c "sleep 15 && npm start"
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: mysql
      DB_NAME: planetario_db
      JWT_SECRET: miclavesupersecreta

  # Frontend (Vite + React)
  frontend:

    # **Desarrollo** descomentar esta linea y comenta la seccion de 'image: …'
    build: ./frontend

    # **Equipo destino**, despues de `docker load -i planetario-frontend-image.tar`:
    # image: planetario-frontend:latest

    restart: on-failure
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:5000  

  # Interfaz de administración de MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: "3306"
      PMA_USER: root
      PMA_PASSWORD: mysql

volumes:
  db_data:
